### ISSUE TITLE
Responsiveness + Routing

### ISSUE THREAD

**Issue by rrrliu** [codebase-berkeley/cofed#17]
Finalize our design and user experience before we present for MSD!

- Add our profile component as the rightmost element within our search page and make it show up when we click a `CardComponent`
- Add all our links between login, register, profile, and table/map view pages (check out our prototyping arrows on Figma!)
- Design a responsive mobile view on Figma

**Comment by leebianca** [comment]
Since the first two bullet points are done already, let's try to fix up the profile page when you click on the user's name in the top right corner to fit well onscreen and have the nav bar on the profile page. Consider removing the blue side border on the profile page.
