### ISSUE TITLE
Filtering

### ISSUE THREAD

**Issue by rrrliu** [codebase-berkeley/cofed#37]
See Bianca's comment below!

Additional notes:
- You may use either path/route parameters or [query parameters](https://masteringjs.io/tutorials/express/query-parameters)
- The `ANY` PostgreSQL keyword may be useful for array inputs, see [this DELETE query](https://masteringjs.io/tutorials/express/query-parameters) for reference
- You will need to make sure the tags in the filter boxes corresponds to the actual values in our `tags` table
- You should be calling this endpoint **anytime a filter changes**

**Comment by leebianca** [comment]
Create a new GET endpoint similar to the the `/api/coops` endpoint that currently exists, and pass in [route parameters](https://expressjs.com/en/guide/routing.html) with the selected filtering tags to the SQL query. FiltersPage should only populate the `coops` state with the filtered coops. This will require joining with the `coop_tags` table and filtering for when the tag is in our selected filtering tags parameter.
