### ISSUE TITLE
Card Component Screen Responsiveness

### ISSUE THREAD

**Issue by jxnelee** [codebase-berkeley/cofed#62]
hi pls fix the card component squish by getting rid of the `max-height = 18vw` in Card.css
do this correctly or caterpillars will manifest in your bed tonight
thank you very much

**Comment by rrrliu** [comment]
good catch! looks like it came from a powerpuff girls commit to me 👀 
https://github.com/codebase-berkeley/cofed/blame/main/client/src/components/Card/Card.css#L13

make a PR and i will deploy it

**Comment by jxnelee** [comment]
caterpillars will be in ur bed tonight
